<?php

return [
    'register-cottage' => 'site/register-cottage',
    'payer-add' => 'site/payer-add',
    'bill-register' => 'site/bill-add',
    'cottage-delete' => 'site/cottage-delete',
    'cottage-add' => 'form/cottage-add',
    'show/<cottageNumber:[0-9\w-]+>' => 'site/show',
    'bank-settings-edit' => 'settings/edit-bank-settings',
    'mail-settings-edit' => 'settings/edit-mail-settings',
    'power-settings-edit' => 'settings/edit-power-settings',
    'bill/<id:[0-9\w-]+>' => 'site/show-bill',
    'pdf/<billId:[0-9\w-]+>' => 'utils/download-pdf',
    'mailing-create' => 'utils/mailing-create',
    'mailing-schedule' => 'site/mailing-schedule',
    'mass-bill/<type:membership|target>' => 'site/mass-bill',
    'mailing-info/<id:[0-9\w-]+>' => 'utils/mailing-info',
    'bill-info/<id:[0-9\w-]+>' => 'utils/bill-info',
    'mailing/<id:[0-9\w-]+>' => 'site/mailing',

    'invoice-printed' => 'utils/invoice-printed',
    'invoice-saved' => 'utils/invoice-saved',
    'send-notifications' => 'utils/send-notifications',
    'cancel-mailing' => 'utils/cancel-mailing',
    'send-message' => 'utils/send-message',
    'get-unsended-messages-count' => 'utils/get-unsended-messages-count',
    'save-mail-template' => 'utils/save-mail-template',
    'save-bill-mail-template' => 'utils/save-bill-mail-template',
    'clear-mailing-schedule' => 'utils/clear-mailing-schedule',
    'delete-mailing' => 'utils/delete-mailing',
    'delete-bills' => 'utils/delete-bills',


    'payer-delete' => 'utils/payer-delete',
    'mail-delete' => 'utils/mail-delete',
    'phone-delete' => 'utils/phone-delete',
    'bill-delete' => 'utils/bill-delete',
    'form/cottage-change/<id:[0-9\w-]+>' => 'form/cottage-change',
    'form/bill-change/<id:[0-9\w-]+>' => 'form/bill-change',
    'form/payer-change/<id:[0-9\w-]+>' => 'form/payer-change',
    'form/mail-change/<id:[0-9\w-]+>' => 'form/mail-change',
    'form/phone-change/<id:[0-9\w-]+>' => 'form/phone-change',
    'form/payer-add/<cottageNumber:[0-9\w-]+>' => 'form/payer-add',
    'form/mail-add/<cottageNumber:[0-9\w-]+>' => 'form/mail-add',
    'form/phone-add/<cottageNumber:[0-9\w-]+>' => 'form/phone-add',
    'form/bill-add/<cottageNumber:[0-9\w-]+>' => 'form/bill-add',
    'form/power-bill-add/<cottageNumber:[0-9\w-]+>' => 'form/power-bill-add',

    'cottage/next' => 'site/next',
    'cottage/previous' => 'site/previous',
    'backup-db' => 'utils/backup-db',
    'download-db-backup' => 'site/download-db',


    'update' => 'utils/update',
];